#!/usr/bin/env bash

function is_sourced() {
  if [ -n "$ZSH_VERSION" ]; then
    case $ZSH_EVAL_CONTEXT in *:file:*) return 0;; esac
  else  # Add additional POSIX-compatible shell names here, if needed.
    case ${0##*/} in dash|-dash|bash|-bash|ksh|-ksh|sh|-sh) return 0;; esac
  fi
  return 1  # NOT sourced.
}

echo $0

is_sourced && sourced=1 || sourced=0

if [ "$0" = "./bmc" ]
then
  echo "RUNNING IN DEVMODE"
  thisdir="$(dirname "$0")"
else
  if [ $sourced -eq 1 ]
  then
    thisdir="$(dirname "$(which bmc)")"
  else
    thisdir="$(dirname "$0")"
  fi
fi

# INCLUDE LIB
source "$thisdir/_bmclib.sh"

CMDS=()
DESC=()
NARGS=$#
ARG1=$1
shift
ARGREST=$@

make_command(){
  CMDS+=("$1")
  DESC+=("$2")
};

make_command "usage" "Show this help."
usage(){
  printf "\nUsage: %s [command]\n\nCommands:\n" $(basename $0);

  i=0
  for cmd in "${CMDS[@]}"
  do
    printf "  %-10s %-40s \n" ${cmd} "${DESC[$i]}";
    i=$((i + 1))
  done
};

runme(){
  if test $NARGS -ge 1;
  then eval "$ARG1" "$ARGREST" ||usage;
  else usage;
  fi;
}

function prelude(){
  loadConfig
  # CHECK deps
  checkdeps "jsonify-aws-dotfiles"
  checkdeps "jq"
  checkdeps "awk"
  checkdeps "assumego"
  checkdeps "gum"
  deps_missing
}

function AWSProfileOrExit(){

  if [ -z $AWS_PROFILE ]
  then
    echo "This command needs AWS_PROFILE to be set. run bmc profsel"
    exit 1
  fi
}

##### PLACE YOUR COMMANDS BELOW #####

make_command "version" "Show bmc version"
version(){
  show_version
}

make_command "profsel" "Set AWS_PROFILE by sourcing this command"
profsel(){

  prelude

  if [[ $# -gt 0 ]]; then
    while getopts 'lp:' opt; do
      case "$opt" in
        l)
          printAWSProfiles
          return
          ;;
        p)
          preferedProfile=$OPTARG
          ;;
        *)
          ;;
      esac
    done
    shift "$(($OPTIND - 1))"
  fi

  selectAWSProfile "$@"
  setMFA

  if [[ -z $selectedProfileName ]]; then
    echo "No profile selected"
  else
    if [ $sourced -eq 1 ]; then
      export AWS_PROFILE=${selectedProfileName}
    else
      echo "Source this script or copy/paste the line below to set profile:"
      echo
      echo "  export AWS_PROFILE=${selectedProfileName}"
      echo
    fi

  fi

}

make_command "console" "Open Firefox with AWS account in console."
console(){

  prelude

  forceProfileSelection=false
  if [[ $# -gt 0 ]]; then
    # Manual parsing to handle -p without value
    while [[ $# -gt 0 ]]; do
      case "$1" in
        -l)
          printAWSProfiles
          return
          ;;
        -p)
          shift
          # Check if next arg exists and doesn't start with -
          if [[ -n $1 && $1 != -* ]]; then
            preferedProfile="$1"
            shift
          else
            forceProfileSelection=true
          fi
          ;;
        -s)
          shift
          if [[ -n $1 ]]; then
            preferedService="$1"
            shift
          fi
          ;;
        *)
          shift
          ;;
      esac
    done
  fi

  # Use AWS_PROFILE if set and not forcing selection
  if [[ -n $AWS_PROFILE && $forceProfileSelection == false && -z $preferedProfile ]]; then
    selectedProfileName=$AWS_PROFILE
    # Determine sourceProfile from AWS_PROFILE for MFA
    selectedProfileARN=$(jsonify-aws-dotfiles | jq -r ".config.\"${AWS_PROFILE}\".role_arn")
    if [[ $selectedProfileARN != "null" && -n $selectedProfileARN ]]; then
      sourceProfile=$(jsonify-aws-dotfiles | jq -r --arg arn "$selectedProfileARN" '.config | to_entries | map(select(.value.role_arn == $arn)) | .[0].value.source_profile // "Error"')
      if [[ ${sourceProfile} == "Error" ]]; then
        sourceProfile=${selectedProfileName}
      fi
    else
      # Profile is in credentials, not config
      sourceProfile=${selectedProfileName}
    fi
  else
    selectAWSProfile
  fi

  setMFA

  GRANTED_ALIAS_CONFIGURED="true" GRANTED_ENABLE_AUTO_REASSUME=tru  assumego --duration 3600s -c $selectedProfileName ${preferedService:+--service "$preferedService"}
}

make_command "ec2ls" "List running ec2's."
ec2ls(){
  prelude
  useOrSelectAWSProfile
  ec2ListInstances
}

make_command "ec2connect" "connect to running ec2."
ec2connect(){
  prelude
  useOrSelectAWSProfile
  $thisdir/ec2connect.sh "$@"
}

make_command "ec2stopstart" "Stop/start ec2 instance"
ec2stopstart(){
  prelude
  useOrSelectAWSProfile
  ec2StopStartInstance "$@"
}

make_command "ec2find" "find ec2 instance"
ec2find(){
  prelude
  useOrSelectAWSProfile
  ec2FindInstance "$@"
}

make_command "ecsconnect" "shell connect to ecs container."
ecsconnect(){
  prelude
  useOrSelectAWSProfile
  $thisdir/ecsconnect.sh
}

##### PLACE YOUR COMMANDS ABOVE #####

runme
